# dbt Project Configuration for Poverty Stoplight Star Schema
name: 'psp_data_build'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project
profile: 'psp_data_build'

# These configurations specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean targets
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  psp_data_build:
    # Default configuration for all models
    +materialized: view

    staging:
      # Staging models: lightweight views for data cleaning
      +materialized: view
      +tags: ['staging']
      +schema: staging

    intermediate:
      # Intermediate models: business logic transformations
      +materialized: view
      +tags: ['intermediate']
      +schema: intermediate

    marts:
      # Marts: final semantic layer tables
      +materialized: table
      +tags: ['mart', 'semantic_layer']
      +schema: marts

      dashboards:
        # Dashboard marts: pre-aggregated for Superset visualization
        +materialized: table
        +tags: ['mart', 'dashboard']
        +schema: dashboards

seeds:
  psp_data_build:
    +schema: seeds

snapshots:
  psp_data_build:
    +target_schema: snapshots
