# dbt Database Connection Profile
# ================================
# Single connection mode - swap credentials in .env as needed
#
# Required Environment Variables:
#   DBT_HOST     - Database host
#   DBT_USER     - Database user
#   DBT_PASSWORD - Database password
#   DBT_DBNAME   - Database name
#   DBT_PORT     - Port (default: 5432)
#   DBT_SCHEMA   - Default schema prefix (default: marts)

psp_data_build:
  target: default
  outputs:
    default:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT', '5432') | as_number }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'marts') }}"
      threads: 4
      keepalives_idle: 0
