# dbt Database Connection Profiles
# This file configures database connection profiles for the TARGET database
# where dbt will build models (marts, staging, etc.)
#
# Source database credentials are configured in models/_sources.yml
# Use environment variables for sensitive information

psp_data_build:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('TARGET_DBT_HOST') }}"
      port: "{{ env_var('TARGET_DBT_PORT', '5432') | as_number }}"
      user: "{{ env_var('TARGET_DBT_USER') }}"
      pass: "{{ env_var('TARGET_DBT_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_DBT_DBNAME') }}"
      schema: "{{ env_var('TARGET_DBT_SCHEMA', 'dbt_dev') }}"
      threads: 4
      keepalives_idle: 0
      sslmode: require

    replica:
      type: postgres
      host: "{{ env_var('REPLICA_DBT_HOST') }}"
      port: "{{ env_var('REPLICA_DBT_PORT', '5432') | as_number }}"
      user: "{{ env_var('REPLICA_DBT_USER') }}"
      pass: "{{ env_var('REPLICA_DBT_PASSWORD') }}"
      dbname: "{{ env_var('REPLICA_DBT_DBNAME') }}"
      schema: "{{ env_var('REPLICA_DBT_SCHEMA', 'public') }}"
      threads: 4
      keepalives_idle: 0
      sslmode: require

    prod:
      type: postgres
      host: "{{ env_var('TARGET_DBT_HOST') }}"
      port: "{{ env_var('TARGET_DBT_PORT', '5432') | as_number }}"
      user: "{{ env_var('TARGET_DBT_USER') }}"
      pass: "{{ env_var('TARGET_DBT_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_DBT_DBNAME') }}"
      schema: dbt_prod
      threads: 4
      keepalives_idle: 0
      sslmode: require

  target: dev
