version: 2

models:
  # ========================================
  # DIMENSION TABLES
  # ========================================

  - name: dim_date
    description: >
      Standard date dimension for time-based analysis.
      Contains ~7,300 rows covering 20 years (2015-2035).
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD integer format (e.g., 20240315)"
        data_tests:
          - unique
          - not_null

      - name: date_actual
        description: "The actual calendar date"
        data_tests:
          - unique
          - not_null

      - name: day_of_week_number
        description: "ISO day number: 1=Monday, 7=Sunday"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]

      - name: month_number
        description: "Month number (1-12)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: quarter_number
        description: "Quarter number (1-4)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]

  - name: dim_organization
    description: >
      Organizational hierarchy combining Application and Organization levels.
      Contains denormalized hierarchy for easier querying.
      Estimated 100-500 rows.
    columns:
      - name: organization_id
        description: "Primary key from ps_network.organizations"
        data_tests:
          - unique
          - not_null

      - name: organization_name
        description: "Organization name"
        data_tests:
          - not_null

      - name: application_id
        description: "Natural key for parent application"
        data_tests:
          - not_null

      - name: application_name
        description: "Application/Hub name"
        data_tests:
          - not_null

  - name: dim_indicator_questions
    description: >
      Indicator dimension with two-level architecture:
      1. MASTER INDICATOR (template) - Canonical English names for aggregation
      2. SURVEY INDICATOR (instance) - Survey-specific translations for drill-down

      One row per survey indicator (survey_stoplight instance).
      Estimated 20,000+ rows (one per survey-indicator combination).

      USAGE:
      - For aggregation/grouping: Use indicator_name (English display name)
      - For drill-down/details: Use survey_indicator_* fields (localized)
    columns:
      - name: survey_indicator_id
        description: "Primary key from data_collect.survey_stoplight (survey-specific)"
        data_tests:
          - unique
          - not_null

      - name: indicator_template_id
        description: "Master template ID from survey_stoplight_indicator"
        data_tests:
          - not_null

      - name: indicator_code_name
        description: "Master indicator code (e.g., 'income') - use for technical joins"
        data_tests:
          - not_null

      - name: indicator_name
        description: "English display name (e.g., 'Income') - PRIMARY FIELD FOR DASHBOARDS"
        data_tests:
          - not_null

      - name: indicator_description
        description: "English description of the master indicator"

      - name: survey_indicator_code_name
        description: "Survey-specific indicator code"
        data_tests:
          - not_null

      - name: survey_indicator_short_name
        description: "Translated indicator name (e.g., 'Ingresos', 'Renda')"

      - name: survey_indicator_question_text
        description: "Translated question text shown to families"

      - name: survey_indicator_description
        description: "Translated description/aspirational text"

      - name: survey_indicator_is_required
        description: "Whether indicator is required in this survey"

      - name: dimension_id
        description: "Dimension category ID (NULL for indicators without dimension assignment)"

      - name: dimension_name
        description: "Dimension category name (standard: 6 poverty dimensions, custom: organization-specific dimensions, NULL if no dimension)"

      - name: red_criteria_description
        description: >
          Description of the critical poverty threshold for this indicator (stoplight value = 1).
          Explains what conditions qualify as "red" status. Example: "Family income is less than $2/day"

      - name: yellow_criteria_description
        description: >
          Description of the moderate poverty threshold for this indicator (stoplight value = 2).
          Explains what conditions qualify as "yellow" status. Example: "Family income is between $2-$4/day"

      - name: green_criteria_description
        description: >
          Description of the non-poor/need met threshold for this indicator (stoplight value = 3).
          Explains what conditions qualify as "green" status. Example: "Family income exceeds $4/day"

  - name: dim_family
    description: >
      Privacy-focused family dimension with minimal PII.
      Coordinates rounded to 2 decimals for privacy.
    columns:
      - name: family_id
        description: "Primary key from ps_families.family"
        data_tests:
          - unique
          - not_null

      - name: is_anonymous
        description: "Privacy flag"
        data_tests:
          - not_null

      - name: country
        description: "Country name"

      - name: latitude
        description: "GPS latitude rounded to 2 decimals for privacy"

      - name: longitude
        description: "GPS longitude rounded to 2 decimals for privacy"

      - name: organization_id
        description: "Foreign key to dim_organization"
        data_tests:
          - not_null
          - relationships:
              field: organization_id
              to: ref('dim_organization')

  - name: dim_survey_definition
    description: >
      Survey template/definition dimension.
      Contains metadata about survey configurations.
      Estimated 20-50 rows.
    columns:
      - name: survey_definition_id
        description: "Primary key from data_collect.survey_definition"
        data_tests:
          - unique
          - not_null

      - name: survey_title
        description: "Survey title"
        data_tests:
          - not_null

  - name: dim_economic_questions
    description: >
      Economic question dimension containing metadata about economic survey questions.

      Contains question definitions (income, assets, employment, housing, etc.) that can be
      included in surveys. Similar structure to dim_indicator_questions but for economic data.

      **Grain:** One row per economic question definition.

      Estimated rows: Varies by number of survey versions, typically 100-500 rows.
    columns:
      - name: survey_economic_id
        description: "Primary key from data_collect.survey_economic"
        data_tests:
          - unique
          - not_null

      - name: survey_definition_id
        description: "Foreign key to survey_definition"
        data_tests:
          - not_null
          - relationships:
              field: survey_definition_id
              to: ref('dim_survey_definition')

      - name: code_name
        description: "Question identifier (e.g., 'householdMonthlyIncome', 'familyCar', 'activityMain')"
        data_tests:
          - not_null

      - name: question_text
        description: "Question displayed to families during survey"

      - name: answer_type
        description: "Response format: text, number, date, select, radio, checkbox, string"
        data_tests:
          - not_null
          - accepted_values:
              values: ['text', 'number', 'date', 'select', 'radio', 'checkbox', 'string']
              config:
                severity: warn

      - name: answer_options
        description: "Available choices for select/radio/checkbox types (JSON or delimited string)"

      - name: scope
        description: "Question scope: family-level or member-level"

      - name: is_for_family_member
        description: "Boolean flag - true if question is for individual family members"

      - name: survey_code
        description: "Survey code from survey_definition"

      - name: survey_title
        description: "Survey title from survey_definition"
        data_tests:
          - not_null

      - name: survey_language
        description: "Survey language code (e.g., 'en', 'es', 'pt')"

  # ========================================
  # FACT TABLES
  # ========================================

  - name: fact_snapshots
    description: >
      Snapshot-level fact table capturing survey event attributes.

      **Grain:** One row per family × snapshot (survey submission).

      Join to fact_indicators via snapshot_id for indicator-level analysis.
      This table captures snapshot-level attributes that apply to all indicators
      within a single survey event.

      Fixes source data integrity issues by recalculating snapshot_number and is_last
      using window functions based on actual chronological order.

      **Key Use Cases:**
      - Cohort analysis: Filter by max_snapshot_number to find families with N+ surveys
      - Time-to-followup: Analyze days_since_baseline distribution
      - Current status: Filter WHERE is_last = TRUE for most recent family state
    columns:
      - name: snapshot_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: family_id
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
          - relationships:
              field: family_id
              to: ref('dim_family')
      - name: organization_id
        description: "Foreign key to dim_organization"
        data_tests:
          - not_null
          - relationships:
              field: organization_id
              to: ref('dim_organization')
      - name: application_id
        description: "Foreign key to applications"
      - name: survey_definition_id
        description: "Foreign key to dim_survey_definition"
        data_tests:
          - not_null
          - relationships:
              field: survey_definition_id
              to: ref('dim_survey_definition')
      - name: project_id
        description: "Foreign key to projects (nullable)"
      - name: date_key
        description: "Foreign key to dim_date (YYYYMMDD integer format)"
        data_tests:
          - not_null
          - relationships:
              field: date_key
              to: ref('dim_date')
      - name: is_anonymous
        description: "Privacy flag - when true, personal data is anonymized"
      - name: stoplight_skipped
        description: "Whether the stoplight section was skipped"
      - name: snapshot_date
        description: "Date when survey was completed"
        data_tests:
          - not_null
      - name: snapshot_created_at
        description: "Record creation timestamp"
      - name: created_by
        description: "User who created the snapshot"
      - name: snapshot_updated_at
        description: "Record last modified timestamp"
      - name: snapshot_number
        description: >
          Recomputed survey round per family+survey_definition.
          1=baseline, >1=follow-up. Calculated chronologically to fix source data issues.
        data_tests:
          - not_null
      - name: is_last
        description: >
          Dynamically computed flag for most recent snapshot per family (across all surveys).
        data_tests:
          - not_null
      - name: is_baseline
        description: "True when snapshot_number = 1 (first survey in family+survey journey)"
        data_tests:
          - not_null
      - name: days_since_baseline
        description: "Days elapsed since baseline survey (0 for baseline, positive for follow-ups)"
        data_tests:
          - not_null
      - name: days_since_previous
        description: "Days elapsed since previous snapshot (NULL for baseline)"
      - name: max_snapshot_number
        description: "Max snapshot number in this family+survey journey (for cohort filtering)"
        data_tests:
          - not_null

  - name: fact_indicators_v2
    description: >
      Enriched indicator fact table with window function columns for progress analysis.

      **Grain:** One row per family × indicator × snapshot.

      Adds baseline_score and previous_score via window functions partitioned by
      family_id + survey_indicator_id, enabling:
      - Sankey diagrams (baseline → current transitions)
      - Progress analysis (current_score - baseline_score)
      - Momentum tracking (current_score - previous_score)

      **Important:** baseline_score is NULL when an indicator was added after the baseline
      survey. Filter WHERE baseline_score IS NOT NULL for valid progress comparisons.

      **Key Patterns:**
      - Sankey diagrams: Filter WHERE is_last = TRUE AND baseline_score IS NOT NULL
      - Progress from start: SELECT *, (current_score - baseline_score) as change WHERE baseline_score IS NOT NULL
      - Recent momentum: SELECT *, (current_score - previous_score) as momentum
    columns:
      - name: date_key
        description: "Foreign key to dim_date (YYYYMMDD integer)"
        data_tests:
          - not_null

      - name: family_id
        description: "Foreign key to dim_family"
        data_tests:
          - not_null

      - name: organization_id
        description: "Foreign key to dim_organization"
        data_tests:
          - not_null

      - name: survey_indicator_id
        description: "Foreign key to dim_indicator_questions"
        data_tests:
          - not_null

      - name: survey_definition_id
        description: "Foreign key to dim_survey_definition"
        data_tests:
          - not_null

      - name: project_id
        description: "Foreign key to stg_projects (nullable)"

      - name: snapshot_id
        description: "Degenerate dimension - source snapshot identifier"
        data_tests:
          - not_null

      - name: snapshot_number
        description: "Survey sequence: 1=baseline, 2+=follow-ups"
        data_tests:
          - not_null

      - name: is_last
        description: "TRUE if this is the family's most recent snapshot"
        data_tests:
          - not_null

      - name: is_baseline
        description: "TRUE if this snapshot is the family's baseline survey (snapshot_number = 1)"
        data_tests:
          - not_null

      - name: max_snapshot_number
        description: "Furthest snapshot this family reached - use for cohort/survivor filtering"
        data_tests:
          - not_null

      - name: current_score
        description: "Indicator value for this snapshot: 0=Skipped, 1=Red, 2=Yellow, 3=Green, NULL=invalid"

      - name: baseline_score
        description: >
          Score from baseline snapshot for this family+indicator.
          NULL if indicator didn't exist in baseline survey (added later).
          Use WHERE baseline_score IS NOT NULL for valid progress comparisons.

      - name: previous_score
        description: "Score from previous snapshot for this family+indicator (NULL for first observation)"

      - name: snapshot_stoplight_id
        description: "Primary key - also serves as FK for joining to stg_snapshot_stoplight_priority/achievement"
        data_tests:
          - unique
          - not_null

      - name: is_priority
        description: "TRUE if family marked this indicator as a priority in this snapshot"
        data_tests:
          - not_null

      - name: has_achievement
        description: "TRUE if family marked this indicator as achieved in this snapshot"
        data_tests:
          - not_null

      - name: was_priority_in_previous
        description: "TRUE if this indicator was a priority in the previous snapshot (for achievement rate analysis)"
