version: 2

models:
  - name: int_baseline_metrics
    description: >
      Baseline survey metrics for families (snapshot_number = 1 only).
      Denormalized view joining fact table with all dimensions.
      Used as source for progress comparison calculations.
    columns:
      - name: family_key
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
      - name: indicator_key
        description: "Foreign key to dim_indicator"
        data_tests:
          - not_null
      - name: snapshot_id
        description: "Snapshot identifier"
        data_tests:
          - not_null
      - name: snapshot_number
        description: "Should always be 1 (baseline)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1]
      - name: indicator_status_value
        description: "Stoplight status: 1=Red, 2=Yellow, 3=Green, NULL=Skipped"

  - name: int_latest_metrics
    description: >
      Latest survey metrics for families (is_last = TRUE only).
      Denormalized view joining fact table with all dimensions.
      Used as source for progress comparison calculations and current status dashboards.
    columns:
      - name: family_key
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
      - name: indicator_key
        description: "Foreign key to dim_indicator"
        data_tests:
          - not_null
      - name: snapshot_id
        description: "Snapshot identifier"
        data_tests:
          - not_null
      - name: snapshot_number
        description: "Survey round number (1 for baseline, 2+ for follow-ups)"
        data_tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 1"
      - name: indicator_status_value
        description: "Stoplight status: 1=Red, 2=Yellow, 3=Green, NULL=Skipped"
