version: 2

models:
  - name: int_snapshot_enriched
    description: "Enriched snapshot data with computed flags and temporal metrics using window functions"
    columns:
      - name: snapshot_id
        description: "Unique identifier for each snapshot"
        data_tests:
          - not_null
          - unique
      - name: family_id
        description: "Foreign key to family dimension"
        data_tests:
          - not_null
      - name: is_baseline
        description: "Derived flag: true when snapshot_number = 1 (baseline survey)"
      - name: is_last_any
        description: "Derived flag: true for the most recent snapshot of each family (regardless of completeness)"
      - name: is_last_with_stoplight
        description: "Derived flag: true for the most recent snapshot with stoplight data (stoplight_skipped=false)"
      - name: days_since_prev
        description: "Calculated metric: days elapsed since the previous snapshot for this family"

  - name: int_indicator_lite
    description: "Lightweight indicator explosion for current state dimension analysis (experimental). Grain: 1 row per indicator per dimension per latest snapshot with stoplight."
    columns:
      - name: indicator_key
        description: "Composite key: snapshot_id || '__' || indicator_code_name || '__' || dimension_id (dimension included since indicators can belong to multiple dimensions)"
        data_tests:
          - not_null
          - unique
      - name: snapshot_id
        description: "Foreign key to snapshot"
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('fact_snapshot')
                field: snapshot_id
      - name: family_id
        description: "Foreign key to family"
        data_tests:
          - not_null
      - name: dimension_id
        description: "Dimension ID from survey_stoplight"
        data_tests:
          - not_null
      - name: indicator_value
        description: "Stoplight color value (1=Red, 2=Yellow, 3=Green)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3]
      - name: indicator_score
        description: "Numeric score (Red=0, Yellow=0.5, Green=1)"
