version: 2

models:
  - name: mart_snapshots
    description: |
      **Primary analytics table for survey completions with poverty scores**

      This mart enables analysis of red/yellow/green indicator distributions,
      poverty score trends, and family-level poverty assessment over time.

      Key metrics:
      - poverty_score: Calculated as (green×3 + yellow×2 + red×1) / (total×3)
      - poverty_category: Non-poor (≥80%), Moderate (60-79%), Severe (<60%)
      - red/yellow/green counts and percentages per survey
    columns:
      - name: snapshot_id
        data_tests: [not_null, unique]
      - name: poverty_score
        description: "Normalized score from 0-1 where 1 = all green indicators"
      - name: poverty_category
        description: "Categorical poverty level based on score thresholds"
        data_tests:
          - accepted_values:
              values: ['Non-poor', 'Moderate poverty', 'Severe poverty', 'Unknown']

  - name: mart_snapshot_indicators
    description: |
      **Detailed indicator-level data for drill-down analysis**

      This mart enables analysis of specific indicators, dimensions,
      and tracking changes in individual poverty measures over time.

      Use this for:
      - Analyzing performance by indicator dimension
      - Tracking improvement in specific poverty areas
      - Understanding which indicators drive overall poverty scores
    columns:
      - name: indicator_response_id
        data_tests: [not_null, unique]
      - name: value_label
        data_tests:
          - accepted_values:
              values: ['Red', 'Yellow', 'Green', 'Unknown']
      - name: mapping_quality
        description: "Data quality flag: 'unique' or 'ambiguous'"
        data_tests:
          - accepted_values:
              values: ['unique', 'ambiguous']