version: 2

models:
  # ========================================
  # DIMENSION TABLES
  # ========================================

  - name: dim_date
    description: >
      Standard date dimension for time-based analysis.
      Contains ~7,300 rows covering 20 years (2015-2035).
    columns:
      - name: date_key
        description: "Surrogate key in YYYYMMDD format (e.g., 20240315)"
        data_tests:
          - unique
          - not_null

      - name: date_actual
        description: "The actual calendar date"
        data_tests:
          - unique
          - not_null

      - name: day_of_week_number
        description: "ISO day number: 1=Monday, 7=Sunday"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7]

      - name: month_number
        description: "Month number (1-12)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: quarter_number
        description: "Quarter number (1-4)"
        data_tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4]

  - name: dim_organization
    description: >
      Organizational hierarchy combining Application and Organization levels.
      Contains denormalized hierarchy for easier querying.
      Estimated 100-500 rows.
    columns:
      - name: organization_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null

      - name: organization_id
        description: "Natural key from ps_network.organizations"
        data_tests:
          - unique
          - not_null

      - name: organization_name
        description: "Organization name"
        data_tests:
          - not_null

      - name: application_id
        description: "Natural key for parent application"
        data_tests:
          - not_null

      - name: application_name
        description: "Application/Hub name"
        data_tests:
          - not_null

  - name: dim_indicator_questions
    description: >
      Indicator dimension with two-level architecture:
      1. MASTER INDICATOR (template) - Canonical English names for aggregation
      2. SURVEY INDICATOR (instance) - Survey-specific translations for drill-down

      One row per survey indicator (survey_stoplight instance).
      Estimated 20,000+ rows (one per survey-indicator combination).

      USAGE:
      - For aggregation/grouping: Use indicator_name (English display name)
      - For drill-down/details: Use survey_indicator_* fields (localized)
    columns:
      - name: indicator_key
        description: "Surrogate key (based on survey_indicator_id)"
        data_tests:
          - unique
          - not_null

      - name: survey_indicator_id
        description: "Natural key from data_collect.survey_stoplight (survey-specific)"
        data_tests:
          - unique
          - not_null

      - name: indicator_id
        description: "Master template ID from survey_stoplight_indicator"
        data_tests:
          - not_null

      - name: indicator_code_name
        description: "Master indicator code (e.g., 'income') - use for technical joins"
        data_tests:
          - not_null

      - name: indicator_name
        description: "English display name (e.g., 'Income') - PRIMARY FIELD FOR DASHBOARDS"
        data_tests:
          - not_null

      - name: indicator_description
        description: "English description of the master indicator"

      - name: survey_indicator_code_name
        description: "Survey-specific indicator code"
        data_tests:
          - not_null

      - name: survey_indicator_short_name
        description: "Translated indicator name (e.g., 'Ingresos', 'Renda')"

      - name: survey_indicator_question_text
        description: "Translated question text shown to families"

      - name: survey_indicator_description
        description: "Translated description/aspirational text"

      - name: survey_indicator_is_required
        description: "Whether indicator is required in this survey"

      - name: dimension_id
        description: "Dimension category ID"
        data_tests:
          - not_null

      - name: dimension_name
        description: "Dimension category name (standard: 6 poverty dimensions, custom: organization-specific dimensions)"
        data_tests:
          - not_null

      - name: red_criteria_description
        description: >
          Description of the critical poverty threshold for this indicator (stoplight value = 1).
          Explains what conditions qualify as "red" status. Example: "Family income is less than $2/day"

      - name: yellow_criteria_description
        description: >
          Description of the moderate poverty threshold for this indicator (stoplight value = 2).
          Explains what conditions qualify as "yellow" status. Example: "Family income is between $2-$4/day"

      - name: green_criteria_description
        description: >
          Description of the non-poor/need met threshold for this indicator (stoplight value = 3).
          Explains what conditions qualify as "green" status. Example: "Family income exceeds $4/day"

  - name: dim_family
    description: >
      Family identity and geography dimension.
      Combines family master data with geographic information.
      Country derived from first family member's birth_country.
      Estimated 3,000-10,000 rows.
    columns:
      - name: family_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null

      - name: family_id
        description: "Natural key from ps_families.family"
        data_tests:
          - unique
          - not_null

      - name: family_code
        description: "Unique family code"
        data_tests:
          - unique
          - not_null

      - name: is_anonymous
        description: "Privacy flag - when true, family_name shows 'ANON_DATA'"
        data_tests:
          - not_null

      - name: latitude
        description: "GPS latitude coordinate (-90 to 90)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "BETWEEN -90 AND 90"
              config:
                where: "latitude is not null"

      - name: longitude
        description: "GPS longitude coordinate (-180 to 180)"
        data_tests:
          - dbt_utils.expression_is_true:
              expression: "BETWEEN -180 AND 180"
              config:
                where: "longitude is not null"

  - name: dim_survey_definition
    description: >
      Survey template/definition dimension.
      Contains metadata about survey configurations.
      Estimated 20-50 rows.
    columns:
      - name: survey_definition_key
        description: "Surrogate key"
        data_tests:
          - unique
          - not_null

      - name: survey_definition_id
        description: "Natural key from data_collect.survey_definition"
        data_tests:
          - unique
          - not_null

      - name: survey_title
        description: "Survey title"
        data_tests:
          - not_null

  - name: dim_economic_questions
    description: >
      Economic question dimension containing metadata about economic survey questions.

      Contains question definitions (income, assets, employment, housing, etc.) that can be
      included in surveys. Similar structure to dim_indicator_questions but for economic data.

      **Grain:** One row per survey_definition + code_name combination.

      Estimated rows: Varies by number of survey versions, typically 100-500 rows.
    columns:
      - name: economic_question_key
        description: "Surrogate key (generated from survey_definition_id + code_name)"
        data_tests:
          - unique
          - not_null

      - name: survey_definition_id
        description: "Natural key - foreign key to survey_definition"
        data_tests:
          - not_null
          - relationships:
              field: survey_definition_id
              to: ref('dim_survey_definition')

      - name: code_name
        description: "Question identifier (e.g., 'householdMonthlyIncome', 'familyCar', 'activityMain')"
        data_tests:
          - not_null

      - name: question_text
        description: "Question displayed to families during survey"

      - name: answer_type
        description: "Response format: text, number, date, select, radio, checkbox"
        data_tests:
          - not_null
          - accepted_values:
              values: ['text', 'number', 'date', 'select', 'radio', 'checkbox']
              config:
                severity: warn

      - name: answer_options
        description: "Available choices for select/radio/checkbox types (JSON or delimited string)"

      - name: scope
        description: "Question scope: family-level or member-level"

      - name: is_for_family_member
        description: "Boolean flag - true if question is for individual family members"

      - name: survey_code
        description: "Survey code from survey_definition"

      - name: survey_title
        description: "Survey title from survey_definition"
        data_tests:
          - not_null

      - name: survey_language
        description: "Survey language code (e.g., 'en', 'es', 'pt')"

  # ========================================
  # FACT TABLES
  # ========================================

  - name: fact_family_indicator_snapshot
    description: >
      Main fact table capturing poverty indicator assessments at atomic grain.

      **Grain:** One row per family, per indicator, per snapshot (survey completion).

      **Row Count:** Estimated 225,000 current rows, growing by ~75K per 1,000 new families.

      **Usage:** This table supports all 20 business questions defined in BUSINESS_QUESTIONS_DOCS.md
      by enabling analysis at family-indicator-snapshot level and aggregation to family-snapshot level.

      **Key Patterns:**
      - Current status: Filter WHERE is_last = TRUE
      - Baseline surveys: Filter WHERE snapshot_number = 1
      - Progress analysis: Compare snapshot_number = 1 vs > 1 for same family
    columns:
      - name: family_indicator_snapshot_key
        description: "Surrogate key for this fact record"
        data_tests:
          - unique
          - not_null

      - name: date_key
        description: "Survey date key in YYYYMMDD format"
        data_tests:
          - not_null
          - relationships:
              field: date_key
              to: ref('dim_date')

      - name: organization_key
        description: "Foreign key to organization dimension"
        data_tests:
          - not_null
          - relationships:
              field: organization_key
              to: ref('dim_organization')

      - name: indicator_key
        description: "Foreign key to indicator dimension"
        data_tests:
          - not_null
          - relationships:
              field: indicator_key
              to: ref('dim_indicator_questions')

      - name: family_key
        description: "Foreign key to family dimension"
        data_tests:
          - not_null
          - relationships:
              field: family_key
              to: ref('dim_family')

      - name: survey_definition_key
        description: "Foreign key to survey definition dimension"
        data_tests:
          - not_null
          - relationships:
              field: survey_definition_key
              to: ref('dim_survey_definition')

      - name: snapshot_id
        description: "Degenerate dimension - natural key from source (data_collect.snapshot.id)"
        data_tests:
          - not_null

      - name: snapshot_number
        description: "Degenerate dimension - survey round: 1=baseline, 2=first follow-up, etc."
        data_tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: is_last
        description: "Degenerate dimension - true if this is the most recent survey for this family"
        data_tests:
          - not_null

      - name: indicator_status_value
        description: "Measure - Stoplight status: 1=Red, 2=Yellow, 3=Green, NULL=Skipped"
        data_tests:
          - accepted_values:
              values: [1, 2, 3]
              config:
                severity: warn
                where: "indicator_status_value is not null"

  - name: fact_family_economic_snapshot
    description: >
      Fact table capturing economic survey responses at atomic grain.

      **Grain:** One row per family, per economic question, per snapshot (survey completion).

      **Scope:** Currently includes 5 priority economic fields:
      - householdMonthlyIncome (+ currency)
      - housingSituation (single-select and multi-select variants)
      - activityMain (single-select, multi-select, and text variants)
      - familyCar (boolean)
      - areaOfResidence (select and radio variants)

      **Multi-type Field Handling:** Fields that exist as different answer types across
      survey versions are represented as separate columns with behavior suffixes
      (e.g., housing_situation_single vs housing_situation_multi).

      **Data Quality Note:** Filters out 244 orphaned code_names (responses without
      matching survey_economic definitions) via inner join in stg_snapshot_economic.
      See DATA_QUALITY.md for details.

      **Row Count:** Estimated 15,000-50,000 rows depending on economic question
      usage across surveys. Grows with new snapshots.
    columns:
      - name: family_economic_snapshot_key
        description: "Surrogate key (generated from snapshot_id + economic_question_key)"
        data_tests:
          - unique
          - not_null

      - name: date_key
        description: "Foreign key to dim_date (survey date in YYYYMMDD format)"
        data_tests:
          - not_null
          - relationships:
              field: date_key
              to: ref('dim_date')

      - name: family_key
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
          - relationships:
              field: family_key
              to: ref('dim_family')

      - name: economic_question_key
        description: "Foreign key to dim_economic_questions"
        data_tests:
          - not_null
          - relationships:
              field: economic_question_key
              to: ref('dim_economic_questions')

      - name: organization_key
        description: "Foreign key to dim_organization"
        data_tests:
          - not_null
          - relationships:
              field: organization_key
              to: ref('dim_organization')

      - name: survey_definition_key
        description: "Foreign key to dim_survey_definition"
        data_tests:
          - not_null
          - relationships:
              field: survey_definition_key
              to: ref('dim_survey_definition')

      - name: snapshot_id
        description: "Degenerate dimension - natural key from source (data_collect.snapshot.id)"
        data_tests:
          - not_null

      - name: snapshot_number
        description: "Degenerate dimension - survey round: 1=baseline, 2=first follow-up, etc."
        data_tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"

      - name: is_last
        description: "Degenerate dimension - true if this is the most recent survey for this family"
        data_tests:
          - not_null

      # Measures - householdMonthlyIncome
      - name: household_monthly_income
        description: "Measure - Monthly household income (numeric value)"

      - name: income_currency_code
        description: "Measure - Currency code for household income (e.g., 'USD', 'EUR', 'BRL')"

      # Measures - housingSituation
      - name: housing_situation_single
        description: "Measure - Housing situation as single-select response (select/radio types)"

      - name: housing_situation_multi
        description: "Measure - Housing situation as multi-select response (checkbox type)"

      # Measures - activityMain
      - name: activity_main_single
        description: "Measure - Main economic activity as single-select response (select/radio types)"

      - name: activity_main_multi
        description: "Measure - Main economic activity as multi-select response (checkbox type)"

      - name: activity_main_text
        description: "Measure - Main economic activity as free text response"

      # Measures - familyCar
      - name: family_car
        description: "Measure - Boolean indicating if family owns a car"

      # Measures - areaOfResidence
      - name: area_of_residence_select
        description: "Measure - Area of residence as detailed select response (specific areas)"

      - name: area_of_residence_radio
        description: "Measure - Area of residence as binary radio response (urban/rural)"
