version: 2

models:
  - name: stg_snapshot
    description: "Cleaned snapshot records with timestamp conversions and standardized boolean flags"
    columns:
      - name: snapshot_id
        description: "Unique identifier for each snapshot"
        data_tests:
          - not_null
          - unique
      - name: family_id
        description: "Foreign key to family dimension"
        data_tests:
          - not_null
      - name: organization_id
        description: "Foreign key to organization dimension"
        data_tests:
          - not_null
      - name: application_id
        description: "Foreign key to application dimension"
        data_tests:
          - not_null
      - name: survey_definition_id
        description: "Foreign key to survey definition dimension"
        data_tests:
          - not_null
      - name: snapshot_number
        description: "Survey round number (1=baseline, >1=follow-up)"
        data_tests:
          - not_null
      - name: snapshot_ts
        description: "Snapshot date/time converted from milliseconds epoch to timestamp"
        data_tests:
          - not_null
      - name: anonymous
        description: "Privacy flag indicating if personal data is anonymized"
      - name: stoplight_skipped
        description: "Flag indicating if stoplight section was skipped"

  - name: stg_family
    description: "Cleaned family records with privacy indicators"
    columns:
      - name: family_id
        description: "Unique identifier for each family"
        data_tests:
          - not_null
          - unique
      - name: organization_id
        description: "Foreign key to organization"
        data_tests:
          - not_null
      - name: application_id
        description: "Foreign key to application"
        data_tests:
          - not_null
      - name: family_code
        description: "Unique family code assigned by organization"
        data_tests:
          - not_null
      - name: is_anonymous
        description: "Privacy flag - when true, PII fields contain 'ANON_DATA'"
      - name: is_active
        description: "Flag indicating if family is currently active"

  - name: stg_organization
    description: "Cleaned organization records"
    columns:
      - name: organization_id
        description: "Unique identifier for each organization"
        data_tests:
          - not_null
          - unique
      - name: application_id
        description: "Foreign key to parent application"
        data_tests:
          - not_null
      - name: organization_name
        description: "Name of the organization"
        data_tests:
          - not_null
      - name: is_active
        description: "Flag indicating if organization is currently active"

  - name: stg_application
    description: "Cleaned application/hub records"
    columns:
      - name: application_id
        description: "Unique identifier for each application"
        data_tests:
          - not_null
          - unique
      - name: application_name
        description: "Name of the application/hub"
        data_tests:
          - not_null
      - name: is_active
        description: "Flag indicating if application is currently active"

  - name: stg_survey_definition
    description: "Cleaned survey definition records"
    columns:
      - name: survey_definition_id
        description: "Unique identifier for each survey definition"
        data_tests:
          - not_null
          - unique
      - name: survey_title
        description: "Title of the survey"
      - name: survey_code
        description: "Unique survey code"
      - name: is_active
        description: "Flag indicating if survey is currently active"
