version: 2

models:
  - name: stg_applications
    description: "Cleaned applications (hubs/platforms) from ps_network schema"
    columns:
      - name: application_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: application_name
        description: "Application/hub name"
        data_tests:
          - not_null

  - name: stg_organizations
    description: "Cleaned organizations implementing surveys"
    columns:
      - name: organization_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: application_id
        description: "Foreign key to applications"
        data_tests:
          - not_null
          - relationships:
              field: application_id
              to: ref('stg_applications')
      - name: organization_name
        description: "Organization name"
        data_tests:
          - not_null

  - name: stg_families
    description: >
      Privacy-focused family records with minimal PII.
      Coordinates rounded to 2 decimals for privacy. Invalid coordinates set to NULL.
    columns:
      - name: family_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: family_is_active
        description: "Whether the family is currently active"
      - name: is_anonymous
        description: "Privacy flag - when true, personal data is anonymized"
        data_tests:
          - not_null
      - name: country
        description: "Country name"
      - name: latitude
        description: "GPS latitude rounded to 2 decimals for privacy"
      - name: longitude
        description: "GPS longitude rounded to 2 decimals for privacy"

  - name: stg_family_members
    description: "Cleaned family member records, used for country derivation"
    columns:
      - name: family_member_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: family_id
        description: "Foreign key to families"
        data_tests:
          - not_null
          - relationships:
              field: family_id
              to: ref('stg_families')

  - name: stg_snapshots
    description: "Cleaned survey snapshot records with converted timestamps"
    columns:
      - name: snapshot_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: family_id
        description: "Foreign key to families"
        data_tests:
          - not_null
          - relationships:
              field: family_id
              to: ref('stg_families')
      - name: organization_id
        description: "Foreign key to organizations"
        data_tests:
          - not_null
          - relationships:
              field: organization_id
              to: ref('stg_organizations')
      - name: snapshot_number
        description: "Survey round: 1=baseline, >1=follow-up"
        data_tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      - name: is_last
        description: "Flag indicating most recent survey for family"
        data_tests:
          - not_null
      - name: snapshot_date
        description: "Date when survey was completed"
        data_tests:
          - not_null

  - name: stg_snapshot_stoplight
    description: >
      Cleaned indicator assessments (stoplight values).

      Contains raw snapshot responses with indicator_code_name for joining to survey_stoplight.
    columns:
      - name: snapshot_stoplight_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: snapshot_id
        description: "Foreign key to snapshots"
        data_tests:
          - not_null
          - relationships:
              field: snapshot_id
              to: ref('stg_snapshots')
      - name: indicator_code_name
        description: "Indicator code name for joining to survey_stoplight"
        data_tests:
          - not_null
      - name: indicator_status_value
        description: "Stoplight status: 1=Red, 2=Yellow, 3=Green, NULL=Skipped"
        data_tests:
          - accepted_values:
              values: [1, 2, 3]
              config:
                severity: warn
                where: "indicator_status_value is not null"

  - name: stg_survey_definitions
    description: "Cleaned survey template definitions"
    columns:
      - name: survey_definition_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: survey_title
        description: "Survey title"
        data_tests:
          - not_null

  - name: stg_survey_stoplight
    description: "Cleaned survey-specific indicator implementations"
    columns:
      - name: survey_indicator_id
        description: "Primary key (survey-specific indicator ID)"
        data_tests:
          - unique
          - not_null
      - name: indicator_code_name
        description: "Unique indicator code"
        data_tests:
          - not_null
      - name: dimension_name
        description: >
          Dimension category name - localized across multiple languages.
          Core English dimensions: Education and Culture, Health and Environment,
          Housing and Infrastructure, Income and Employment, Interiority and Motivation,
          Organization and Participation.
          Note: Dimension names vary by survey language and may include translations
          in Spanish, French, Arabic, Russian, and many other languages.
        data_tests:
          - not_null

  - name: stg_survey_stoplight_indicator
    description: "Cleaned master indicator templates"
    columns:
      - name: indicator_template_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: indicator_template_code_name
        description: "Unique template code"
        data_tests:
          - not_null

  - name: stg_survey_stoplight_dimension
    description: "Cleaned poverty dimension categories (6 canonical + custom dimensions)"
    columns:
      - name: dimension_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: dimension_code
        description: "Dimension code (e.g., 'incomeAndEmployment')"
      - name: dimension_met_name
        description: "Normalized translation key for dimension name lookup (lowercase)"

  - name: stg_survey_stoplight_color
    description: >
      Color criteria descriptions for each survey indicator.

      Contains one row per indicator per color value (red/yellow/green).
      Used by dim_indicator_questions to provide color-level threshold descriptions.
    columns:
      - name: survey_stoplight_color_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: survey_indicator_id
        description: "Foreign key to survey_stoplight"
        data_tests:
          - not_null
      - name: color_value
        description: "Stoplight color value (1=red, 2=yellow, 3=green)"
      - name: color_description
        description: "Description of the threshold criteria for this color"

  - name: stg_survey_economic
    description: >
      Cleaned economic question definitions from survey_economic.

      Contains the master catalog of economic questions (income, assets, employment, etc.)
      that can be included in surveys. Questions are defined per survey_definition.
    columns:
      - name: survey_economic_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: survey_definition_id
        description: "Foreign key to survey_definition"
        data_tests:
          - not_null
      - name: code_name
        description: "Question identifier (e.g., 'householdMonthlyIncome', 'familyCar')"
        data_tests:
          - not_null
      - name: answer_type
        description: "Response format: text, number, date, select, radio, checkbox"
        data_tests:
          - not_null

  - name: stg_snapshot_economic
    description: >
      Cleaned economic survey responses from snapshot_economic.

      Contains actual family responses to economic questions.
    columns:
      - name: snapshot_economic_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: snapshot_id
        description: "Foreign key to snapshots"
        data_tests:
          - not_null
          - relationships:
              field: snapshot_id
              to: ref('stg_snapshots')
      - name: code_name
        description: "Question identifier matching survey_economic.code_name"
        data_tests:
          - not_null
      - name: answer_type
        description: "Response format type"
        data_tests:
          - not_null

  - name: stg_snapshot_stoplight_priority
    description: "Cleaned priority indicators from snapshot_stoplight_priority"
    columns:
      - name: snapshot_stoplight_priority_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: snapshot_stoplight_id
        description: "Foreign key to snapshot_stoplight"
        data_tests:
          - not_null
          - relationships:
              field: snapshot_stoplight_id
              to: ref('stg_snapshot_stoplight')
      - name: reason
        description: "Reason given for selecting this priority"
      - name: action
        description: "Planned action to address the priority"
      - name: estimated_date
        description: "Months to improve (estimated)"

  - name: stg_snapshot_stoplight_achievement
    description: "Cleaned achievement records from snapshot_stoplight_achievement"
    columns:
      - name: snapshot_stoplight_achievement_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: snapshot_stoplight_id
        description: "Foreign key to snapshot_stoplight"
        data_tests:
          - not_null
          - relationships:
              field: snapshot_stoplight_id
              to: ref('stg_snapshot_stoplight')
      - name: action
        description: "Action taken to achieve the result"
      - name: roadmap
        description: "Steps taken/planned"

  - name: stg_countries
    description: "ISO country codes and names reference table"
    columns:
      - name: country_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: country_code
        description: "ISO 3166-1 alpha-2 code (e.g., 'US', 'GB')"
        data_tests:
          - not_null
      - name: country_name
        description: "Full country name (e.g., 'United States')"
        data_tests:
          - not_null
