version: 2

models:
  - name: mart_snapshot_current
    description: "Current status view showing the most recent snapshot for each family. Filters fact_snapshot where is_last_any=true."
    columns:
      - name: snapshot_id
        description: "Primary key - unique identifier for each snapshot"
        data_tests:
          - not_null
          - unique
      - name: family_id
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
      - name: is_last_any
        description: "Should always be true in this view"

  - name: mart_snapshot_baseline
    description: "Baseline view showing the initial snapshot for each family. Filters fact_snapshot where is_baseline=true."
    columns:
      - name: snapshot_id
        description: "Primary key - unique identifier for each snapshot"
        data_tests:
          - not_null
      - name: family_id
        description: "Foreign key to dim_family"
        data_tests:
          - not_null
      - name: is_baseline
        description: "Should always be true in this view"
      - name: snapshot_number
        description: "Should always be 1 in this view"
