version: 2

sources:
  - name: ps_network
    description: "Network and organizational data"
    schema: ps_network
    tables: []

  - name: data_collect
    description: "Data collection and survey information"
    schema: data_collect
    tables:
      - name: snapshot
        description: "Survey completions by families"
      - name: snapshot_stoplight
        description: "Indicator responses from survey completions"
      - name: survey_stoplight_indicator
        description: "Master catalog of indicator templates"
      - name: survey_stoplight
        description: "Survey-specific indicator definitions"
      - name: survey_definition
        description: "Survey configuration and metadata"

  - name: library
    description: "Reference and lookup data"
    schema: library
    tables: []

  - name: ps_families
    description: "Family and participant data"
    schema: ps_families
    tables:
      - name: family
        description: "Family master data"

  - name: ps_solutions
    description: "Solutions and interventions data"
    schema: ps_solutions
    tables: []

models:
  - name: stg_snapshot
    description: "Simple snapshot data with clean column names"
    columns:
      - name: snapshot_id
        data_tests: [not_null, unique]

  - name: stg_snapshot_stoplight
    description: "Simple indicator responses with clean column names"
    columns:
      - name: indicator_response_id
        data_tests: [not_null, unique]

  - name: stg_survey_stoplight
    description: "Simple indicator definitions with clean column names"
    columns:
      - name: definition_id
        data_tests: [not_null, unique]

  - name: stg_indicators
    description: "Simple master indicator catalog with clean column names"
    columns:
      - name: indicator_master_id
        data_tests: [not_null, unique]

  - name: stg_family
    description: "Simple family data with clean column names"
    columns:
      - name: family_id
        data_tests: [not_null, unique]

  - name: stg_survey_definition
    description: "Simple survey metadata with clean column names"
    columns:
      - name: id
        data_tests: [not_null, unique]